services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    stdin_open: true
    tty: true
    networks:
      - app-network
    command: npm run start

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge
