services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  # Ensure backend is exposed on 8000
    stdin_open: true
    tty: true