services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules

    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
